import React from "react";
import {
  Search,
  Download,
  Calendar,
  FileText,
} from "lucide-react";

const reports = [
  {
    id: "REP001",
    title: "Monthly Revenue Report",
    generatedBy: "Admin",
    date: "13 Jun 2026",
    status: "Ready",
  },
  {
    id: "REP002",
    title: "User Registration Report",
    generatedBy: "System",
    date: "12 Jun 2026",
    status: "Ready",
  },
  {
    id: "REP003",
    title: "Station Performance Report",
    generatedBy: "Admin",
    date: "11 Jun 2026",
    status: "Processing",
  },
];

export default function Reports() {
  return (
    <div className="space-y-6">

      {/* Top Controls */}

      <div className="flex flex-col lg:flex-row justify-between gap-4">

        {/* Search */}

        <div className="relative w-full lg:w-96">

          <Search
            size={18}
            className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
          />

          <input
            type="text"
            placeholder="Search reports..."
            className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-11 pr-4 outline-none focus:ring-2 focus:ring-blue-200"
          />

        </div>

        {/* Right Controls */}

        <div className="flex gap-3">

          <button className="flex items-center gap-2 border border-slate-200 bg-white px-5 py-3 rounded-xl hover:bg-slate-50">

            <Calendar size={18} />

            Select Date

          </button>

          <button className="flex items-center gap-2 bg-blue-900 text-white px-5 py-3 rounded-xl hover:bg-blue-800">

            <Download size={18} />

            Generate Report

          </button>

        </div>

      </div>

      {/* Reports Table */}

      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">

        <table className="w-full">

          <thead className="bg-slate-50">

            <tr>

              <th className="px-6 py-4 text-left">Report ID</th>

              <th className="px-6 py-4 text-left">Title</th>

              <th className="px-6 py-4 text-left">Generated By</th>

              <th className="px-6 py-4 text-left">Date</th>

              <th className="px-6 py-4 text-left">Status</th>

              <th className="px-6 py-4 text-left">Download</th>

            </tr>

          </thead>

          <tbody>

            {reports.map((report) => (

              <tr
                key={report.id}
                className="border-t border-slate-100 hover:bg-slate-50"
              >

                <td className="px-6 py-4 font-medium">
                  {report.id}
                </td>

                <td className="px-6 py-4">
                  {report.title}
                </td>

                <td className="px-6 py-4">
                  {report.generatedBy}
                </td>

                <td className="px-6 py-4">
                  {report.date}
                </td>

                <td className="px-6 py-4">

                  <span
                    className={`px-3 py-1 rounded-full text-sm ${
                      report.status === "Ready"
                        ? "bg-green-100 text-green-700"
                        : "bg-yellow-100 text-yellow-700"
                    }`}
                  >
                    {report.status}
                  </span>

                </td>

                <td className="px-6 py-4">

                  <button className="flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-900 text-white hover:bg-blue-800">

                    <FileText size={16} />

                    Download

                  </button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
}